### ISSUE TITLE
[vmware-iso] unable to detect platform

### ISSUE THREAD

**Issue by username-is-already-taken2** [mondoolabs/packer-provisioner-mondoo#2] opened 2020-08-28 10:34 UTC
Hi 

When integrating mondoo into my packer run using the vmware-iso builder I'm not able to run the provider.

When it attempts to run a scan it can't identify the platform (which in my case is centos 7 (2003))

I'll attach the packer configuration shortly but I wanted to share the debug in case that helps in the first instance.

![image](https://user-images.githubusercontent.com/13700297/91551106-91f27500-e921-11ea-8f79-d89635e042e1.png)

What's interesting is that it can't parse the os-release (`/etc/os-release`?) file but looking at what it got, its looks like the details of the symbolic link (`/usr/lib/os-release`) file size etc

I'll follow up with the packer config shortly

Best Regards

Gary

**Comment by chris-rock** [comment] 2020-08-28 11:08
I experienced some issues with packers ssh proxy and centos in the past. That is why we switched to scp file transfer. I do not have a vsphere environment but I am going to test a build with centos 7 to ensure it is not a general issue. If that works, we need to investigate if this is a issue in combination with the vmware-iso builder.

**Comment by chris-rock** [comment] 2020-08-28 11:59
I am able to reproduce the issue. Therefore it is not related to the vmware-iso builder. I'll let you know as soon as I have an update.

**Comment by chris-rock** [comment] 2020-08-28 12:13
Using packer's debug mode, I am able to connect and scan the instance. Therefore the issue is related to packers ssh proxy again 😔.

<img width="903" alt="Screenshot 2020-08-28 at 14 12 10" src="https://user-images.githubusercontent.com/1178413/91559485-78105c80-e938-11ea-869c-bf629f236cbd.png">

**Comment by chris-rock** [comment] 2020-08-28 14:28
This issue is fixed in mondoo 0.61.1. The packer plugin will not require an update. We made our scp implement more robust and handle missing time header properly now.

<img width="1116" alt="Screenshot 2020-08-28 at 16 28 12" src="https://user-images.githubusercontent.com/1178413/91579146-78662300-e94b-11ea-8b79-70c2b172ed91.png">

**Closed by chris-rock** 2020-08-28 14:28 UTC
